### ISSUE TITLE
Support retrieval of array argument from TemplateTag

### ISSUE THREAD

**Issue by ttveldhuis** [xentriq/xentriq#102]
```
TemplateTag $tag ...
$tag->fetchArrayArgument(...);
```

```
[tag... array="1,2,3"]
```

Should result in 

```
array(1,2,3)
```

**Comment by mpwaldhorst** [comment]
Not sure about the use cases of this as it seems very specific.

Is this not equivalent to simply using `explode` on the tag argument?

**Comment by ttveldhuis** [comment]
Suggestion is to add this to the ```StringUtils``` to support error handling default values for ```explode```.

```StringUtils::split($string, $delimiter = ',', $default = array());```
