### ISSUE TITLE
Passing exception to Actions::addError doesn't allow proper access to the exception

### ISSUE THREAD

**Issue by ttveldhuis** [xentriq/xentriq#103]
Passing exception to ```Actions::addError``` doesn't allow proper access to the exception. Message and other attributes are unavailable when trying to access them through for example ```[errors json]```.

**Comment by mpwaldhorst** [comment]
This is probably more related to it being an object. In my project needed to convert to an array to be able to access the information.

In my case this was for an exception containing a list of validation errors. Will probably have to do some custom stuff anyway for that.

However being able to just pass a stdClass or custom class would be cool.

**Comment by ttveldhuis** [comment]
> This is probably more related to it being an object. In my project needed to convert to an array to be able to access the information.

Problem I saw with that is that the relevant fields of the Exception (and related) are protected, and will not be added to an array doing a cast (`(array) $exception`)
