### ISSUE TITLE
Determine whether to introduce more type-safety (not compatible with PHP7.0)

### ISSUE THREAD

**Issue by ttveldhuis** [xentriq/xentriq#75]
For Xentriq v1.0 we have made a good start in implementing type-safety (#70). There are currently a lot of restrictions in doing so because of the support for PHP7.0. For example, nullable type specification is not supported.

We need to decide whether to keep support for PHP7.0 or move forward with the more advanced features in PHP7.1

**Comment by mpwaldhorst** [comment]
Looking at PHP support on different OSes this is a bit of difficult discussion, for now Ubuntu 16.04 for example comes with 7.0 whereas the newly released 18.04 LTS comes with 7.2. And then of course there is other distros like CentOS.

On the other hand on all of those you can always use EPEL or equivalent to get at least 7.1 so it should not really be a complete blocker in that regard.

From Docker point of view there is no issue as one can use the official PHP images.

I guess as anyone that is going to use Xentriq going forward will be creating either a new project or migrating in any case asking for at least PHP 7.1 should not be too much of a stretch.
What do you think? Where do you think there might be an issue?

**Comment by ttveldhuis** [comment]
From 2.0.0 an onward we will only support PHP 7.1 and up.
